#
# sub-SConscript file for the examples
#

import os

# import everything exported in SConstruct

Import('*')

# Place examples in a bin subdirectory

INSTALLDIR=INSTALLDIR+"/bin/"+INSTALLDIR_PREFIX

for example in Glob("*",strings=True):
  if os.path.isdir(example):
    SConscript(example+"/SConscript",
               exports=["mode","mcu","hse","env","systemprefix","INSTALLDIR","VERSION","example"],
               variant_dir=example+"/build/"+systemprefix,
               duplicate=0)
