#
# sub-SConscript file for the examples
#

import os

# import everything exported in SConstruct

Import('*')

for example in Glob("*",strings=True):
  if os.path.isdir(example) and example != "system":
    SConscript(example+"/SConscript",
               exports=["mode","mcu","hse","env","systemprefix","INSTALLDIR","VERSION","example"],
               variant_dir=example+"/build/"+mode+"-"+mcu+"-"+hse,
               duplicate=0)
